<?php

namespace PHPCanvas\Exception;

enum ContainerError: string
{
	case LOAD_FAILURE = 'CONTAINER_LOAD_FAILURE';
	case TYPE_FAILURE = 'CONTAINER_TYPE_FAILURE';
	case CREATE_FAILURE = 'CONTAINER_CREATE_FAILURE';
	case NOT_OBJECT = 'CONTAINER_NOT_OBJECT';
	case INSTANTIATE_FAILURE = 'CONTAINER_INSTANTIATE_FAILURE';
	case CLASS_NOT_FOUND = 'CONTAINER_CLASS_NOT_FOUND';
	case CALL_FAILURE = 'CONTAINER_CALL_FAILURE';
}
